# This is a GitHub Actions workflow file.
# It defines a set of automated jobs that run in response to events.

# Name of the workflow, which will be displayed on the "Actions" tab in GitHub
name: Backend CI/CD & Security Pipeline

# This specifies the trigger for the workflow.
# It will run on every push event to the "main" branch.
on:
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # This job is named "build-and-test"
  build-and-test:
    # This specifies that the job will run on the latest version of an Ubuntu virtual machine.
    runs-on: ubuntu-latest

    # The steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # Step 1: Check out your repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up the Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use Node.js version 20

      # Step 3: Install dependencies for the backend
      # This step runs 'npm install' inside the 'server' directory.
      - name: Install server dependencies
        run: cd server && npm install

      # Step 4: Build the TypeScript code
      # This is our Continuous Integration check. It runs the 'build' script
      # from the server's package.json file. If tsc finds any TypeScript
      # errors, this step will fail.
      - name: Build backend project
        run: cd server && npm run build
      
      # Step 5: Sonarqube Scan (Static Code Analysis)
      # This step runs a static analysis scan to check for bugs, vulnerabilities,
      # and code smells. It acts as a Quality Gate.
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  # This job depends on the successful completion of "build-and-test"
  containerize-and-scan:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx
      # This action sets up the Docker build environment.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Build the Docker image
      # This step builds the Docker image using the Dockerfile in the 'server' directory.
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: false # We are not pushing to a registry yet
          tags: calyte-backend:latest
          load: true # Load the image into the runner for scanning

      # Step 4: Trivy Scan (Vulnerability Scanning)
      # This step scans the built Docker image for known vulnerabilities.
      # If high or critical vulnerabilities are found, the pipeline will fail.
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'calyte-backend:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
